### ISSUE TITLE
Google Calendars & Docs Embedding

### ISSUE THREAD

**Issue by joewheaton** [joewheaton-org/River-Styles-Workshop#2]
One of the things I have a lot of is Google Calendars and Docs embedded in pages (especially on course and workshop sites - e.g.  [Workshop Schedule](http://riverstyles.joewheaton.org/syllabus/workshop-schedules/2013-WATS-6900); e.g. [Syllabus](http://riverstyles.joewheaton.org/syllabus/workshop-schedules/2013-Workshop-Schedule)).  With traditional HTML, you simply go to Calendar Details and grab the 
``` html
 <iframe src="https://calendar.google.com/calendar/embed?src=d2dpdd8sqi24tpa26lorsani4k%40group.calendar.google.com&ctz=America/Denver" 
style="border: 0" width="800" height="600" frameborder="0" scrolling="no">
</iframe> 
```
and dump it in your code. With Google Sites, there is a special and annoying widget for adding them as a 'Gadget'.  **How do you add Google Calendars and Documents with mark down and JSON**? I found [this post](https://www.kacurak.com/blog/turn-google-calendar-into-events-list-on-website), which seems unnecessarily finicky and complicated. I'm hoping you have a simple trick up the sleeve?

**Comment by philipbaileynar** [comment]
IFrames work... there might be slicker ways of embedding though
