### ISSUE TITLE
links not working

### ISSUE THREAD

**Issue by lhaycock** [joewheaton-org/River-Styles-Workshop#5]
Can you please help me understand why none of the links to Day 1, 2, and 3 are working in the topics section?  They are not working from the index page or from the a, b, c, etc sections.  I am getting an error that says file not found. @philipbaileynar @joewheaton

**Comment by joewheaton** [comment]
So am I right in thinking @lhaycock  that you figured this out? I think you said its case sensitive?

So your old Day 1 link was [https://joewheaton-org.github.io/River-Styles-Workshop/Topics/Day1/day1.html](https://joewheaton-org.github.io/River-Styles-Workshop/Topics/Day1/day1.html)

The correct link is [https://joewheaton-org.github.io/River-Styles-Workshop/Topics/Day1/day-1.html](https://joewheaton-org.github.io/River-Styles-Workshop/Topics/Day1/day-1.html)

PS - as you post issues, don't forget to provide hyperlinks to the pages or things you're questioning about to make it more specific and easier for others to help you. Also, don't forget to include any code snippets where appropriate.

**Comment by lhaycock** [comment]
Yes, thanks for the clarification @joewheaton
